DROP TABLE IF EXISTS `images`;

CREATE TABLE `images` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `alt` text COLLATE utf8mb4_unicode_ci,
  `note` text COLLATE utf8mb4_unicode_ci,
  `filename` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=137 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


insert into images values (null, null, null, "01_20_0.jpg", now(), now()),
(null, null, null, "01_20_10.jpg", now(), now()),
(null, null, null, "01_20_11.jpg", now(), now()),
-- (null, null, null, "01_20_12.jpg", now(), now()),
-- (null, null, null, "01_20_13.jpg", now(), now()),
(null, null, null, "01_20_14.jpg", now(), now()),
-- (null, null, null, "01_20_15.jpg", now(), now()),
(null, null, null, "01_20_16.jpg", now(), now()),
-- (null, null, null, "01_20_17.jpg", now(), now()),
-- (null, null, null, "01_20_18.jpg", now(), now()),
(null, null, null, "01_20_20.jpg", now(), now()),
(null, null, null, "01_20_24.jpg", now(), now()),
(null, null, null, "01_20_25.jpg", now(), now()),
(null, null, null, "01_20_26.jpg", now(), now()),
(null, null, null, "01_20_29.jpg", now(), now()),
-- (null, null, null, "01_20_2.jpg", now(), now()),
(null, null, null, "01_20_30.jpg", now(), now()),
(null, null, null, "01_20_34.jpg", now(), now()),
(null, null, null, "01_20_3.jpg", now(), now()),
(null, null, null, "01_20_4.jpg", now(), now()),
(null, null, null, "01_20_5.jpg", now(), now()),
(null, null, null, "01_20_6.jpg", now(), now()),
-- (null, null, null, "01_20_7.jpg", now(), now()),
(null, null, null, "01_20_9.jpg", now(), now()),
(null, null, null, "100_0016.jpg", now(), now()),
(null, null, null, "100_0017.jpg", now(), now()),
(null, null, null, "100_0018.jpg", now(), now()),
(null, null, null, "1.jpg", now(), now()),
(null, null, null, "20021.jpg", now(), now()),
(null, null, null, "20022.jpg", now(), now()),
(null, null, null, "2.jpg", now(), now()),
(null, null, null, "3.jpg", now(), now()),
(null, null, null, "01_20_2.jpg", now(), now()),
-- (null, null, null, "4.jpg", now(), now()),
-- (null, null, null, "5.jpg", now(), now()),
-- (null, null, null, "6.jpg", now(), now()),
(null, null, null, "7.jpg", now(), now()),
(null, null, null, "8.jpg", now(), now()),
(null, null, null, "9.jpg", now(), now()),
(null, null, null, "a.jpg", now(), now()),
(null, null, null, "b.jpg", now(), now()),
(null, null, null, "c.jpg", now(), now()),
(null, null, null, "Dad-18.6.1919.jpg", now(), now()),
-- (null, null, null, "Dad-&-Dermott-Dunleavy.jpg", now(), now()),
(null, null, null, "Dad-School-photo-c.-1927.jpg", now(), now()),
(null, null, null, "DSC01245.jpg", now(), now()),
(null, null, null, "DSCF0542.jpg", now(), now()),
(null, null, null, "DSCF0543.jpg", now(), now()),
(null, null, null, "DSCF0544.jpg", now(), now()),
(null, null, null, "DSCF0834.jpg", now(), now()),
(null, null, null, "DSCF0835.jpg", now(), now()),
(null, null, null, "DSCF0836.jpg", now(), now()),
(null, null, null, "DSCN0384.jpg", now(), now()),
-- (null, null, null, "DSCN0385.jpg", now(), now()),
-- (null, null, null, "DSCN0386.jpg", now(), now()),
(null, null, null, "DSCN0387.jpg", now(), now()),
(null, null, null, "DSCN0388.jpg", now(), now()),
(null, null, null, "DSCN0389.jpg", now(), now()),
(null, null, null, "DSCN0390.jpg", now(), now()),
(null, null, null, "DSCN0391.jpg", now(), now()),
(null, null, null, "DSCN0392.jpg", now(), now()),
(null, null, null, "DSCN0393.jpg", now(), now()),
(null, null, null, "DSCN0394.jpg", now(), now()),
(null, null, null, "DSCN0461.jpg", now(), now()),
(null, null, null, "DSCN0466.jpg", now(), now()),
(null, null, null, "DSCN0467.jpg", now(), now()),
(null, null, null, "DSCN0468.jpg", now(), now()),
(null, null, null, "DSCN0469.jpg", now(), now()),
(null, null, null, "DSCN0476.jpg", now(), now()),
(null, null, null, "DSCN0477.jpg", now(), now()),
(null, null, null, "DSCN0478.jpg", now(), now()),
(null, null, null, "DSCN2208.jpg", now(), now()),
(null, null, null, "DSCN2703.jpg", now(), now()),
(null, null, null, "DSCN2704.jpg", now(), now()),
(null, null, null, "DSCN2705.jpg", now(), now()),
(null, null, null, "DSCN2706.jpg", now(), now()),
(null, null, null, "DSCN2707.jpg", now(), now()),
(null, null, null, "DSCN2708.jpg", now(), now()),
(null, null, null, "DSCN2709.jpg", now(), now()),
(null, null, null, "DSCN2710.jpg", now(), now()),
(null, null, null, "DSCN2711.jpg", now(), now()),
(null, null, null, "DSCN2712.jpg", now(), now()),
(null, null, null, "DSCN2713.jpg", now(), now()),
(null, null, null, "DSCN2714.jpg", now(), now()),
(null, null, null, "DSCN2715.jpg", now(), now()),
(null, null, null, "DSCN2716.jpg", now(), now()),
(null, null, null, "DSCN2717.jpg", now(), now()),
(null, null, null, "DSCN2718.jpg", now(), now()),
(null, null, null, "DSCN2719.jpg", now(), now()),
(null, null, null, "DSCN2720.jpg", now(), now()),
(null, null, null, "DSCN2721.jpg", now(), now()),
(null, null, null, "DSCN2722.jpg", now(), now()),
(null, null, null, "DSCN2723.jpg", now(), now()),
(null, null, null, "DSCN2724.jpg", now(), now()),
(null, null, null, "DSCN2725.jpg", now(), now()),
(null, null, null, "DSCN2726.jpg", now(), now()),
(null, null, null, "DSCN2727.jpg", now(), now()),
(null, null, null, "DSCN2728.jpg", now(), now()),
(null, null, null, "DSCN2729.jpg", now(), now()),
(null, null, null, "DSCN2730.jpg", now(), now()),
(null, null, null, "DSCN2731.jpg", now(), now()),
(null, null, null, "File0005.jpg", now(), now()),
(null, null, null, "File0010.jpg", now(), now()),
(null, null, null, "File0011.jpg", now(), now()),
(null, null, null, "File0014.jpg", now(), now()),
(null, null, null, "File0015.jpg", now(), now()),
(null, null, null, "Ken,-Granny,-Mary,-Matt-and-Batt-&-Dad-behind.jpg", now(), now()),
(null, null, null, "Kennedy,-Batt,-Mary,-Granny,-Dad,-GrandDad,-Matt.jpg", now(), now()),
(null, null, null, "Maureen-OBrien-10.8.1921.jpg", now(), now()),
(null, null, null, "Michele-OBrien,-2nd-row,-4th-from-left.jpg", now(), now()),
(null, null, null, "Mums-80th-birthday.jpg", now(), now()),
(null, null, null, "Nancy-&-Tom-OBrien.jpg", now(), now()),
-- (null, null, null, "OBrienFamily-003.jpg", now(), now()),
(null, null, null, "OBrienFamily-004.jpg", now(), now()),
(null, null, null, "OBrienFamily-005.jpg", now(), now()),
(null, null, null, "OBrienFamily-006.jpg", now(), now()),
-- (null, null, null, "OBrienFamily-007.jpg", now(), now()),
(null, null, null, "OBrienFamily-009.jpg", now(), now()),
-- (null, null, null, "OBrienFamily-010.jpg", now(), now()),
(null, null, null, "OBrienFamily-011.jpg", now(), now()),
(null, null, null, "OBrienFamily-012.jpg", now(), now()),
(null, null, null, "OBrienFamily-013.jpg", now(), now()),
(null, null, null, "Picture-001.jpg", now(), now()),
(null, null, null, "Picture-002.jpg", now(), now()),
(null, null, null, "Picture-003.jpg", now(), now()),
(null, null, null, "Poppy.jpg", now(), now()),
(null, null, null, "Tom.jpg", now(), now()),
(null, null, null, "Tom-&-Maureen-OBrien5.9.1949.jpg", now(), now()),
(null, null, null, "Tom-&-Michele.jpg", now(), now()),
(null, null, null, "Tom--Mollie-OBrien-with-family-at-Clonerk.jpg", now(), now()),
(null, null, null, "Tom-OBrien-18.6.1919.jpg", now(), now()),
-- (null, null, null, "Tom-OBrien---back,-left.jpg", now(), now()),
-- (null, null, null, "Untitled-10.jpg", now(), now()),
-- (null, null, null, "Untitled-11.jpg", now(), now()),
(null, null, null, "Untitled-12.jpg", now(), now()),
(null, null, null, "Untitled-13.jpg", now(), now()),
(null, null, null, "Untitled-14.jpg", now(), now()),
(null, null, null, "Untitled-15.jpg", now(), now()),
(null, null, null, "Untitled-16.jpg", now(), now()),
(null, null, null, "Untitled-17.jpg", now(), now()),
(null, null, null, "Untitled-18.jpg", now(), now()),
(null, null, null, "Untitled-19.jpg", now(), now()),
(null, null, null, "Untitled-1.jpg", now(), now()),
(null, null, null, "Untitled-20.jpg", now(), now()),
(null, null, null, "Untitled-21.jpg", now(), now()),
(null, null, null, "Untitled-22.jpg", now(), now()),
(null, null, null, "Untitled-23.jpg", now(), now()),
(null, null, null, "Untitled-24.jpg", now(), now()),
-- (null, null, null, "Untitled-25.jpg", now(), now()),
-- (null, null, null, "Untitled-26.jpg", now(), now()),
(null, null, null, "Untitled-2.jpg", now(), now()),
(null, null, null, "Untitled-3.jpg", now(), now()),
(null, null, null, "Untitled-4.jpg", now(), now()),
(null, null, null, "Untitled-5.jpg", now(), now()),
-- (null, null, null, "Untitled-6.jpg", now(), now()),
(null, null, null, "Untitled-7.jpg", now(), now()),
(null, null, null, "Untitled-8.jpg", now(), now()),
(null, null, null, "Untitled-9.jpg", now(), now());
